### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ebugarin** [insidesherpa/JPMC-tech-task-1#15]
I am using Windows 10, after downloading python 3.8 and pip for python 3, i get this message in the final steps 
<img width="685" alt="22" src="https://user-images.githubusercontent.com/57426824/68266542-036cda00-0015-11ea-9577-9bd952ef6172.PNG">
<img width="659" alt="33" src="https://user-images.githubusercontent.com/57426824/68266615-3616d280-0015-11ea-9f03-689815022764.PNG">

**Comment by jbf-insidesherpa** [comment]
@ebugarin you're using the wrong repository. You should have cloned this other repository for it to work
https://github.com/insidesherpa/JPMC-tech-task-1-PY3

**Comment by ebugarin** [comment]
I managed to finish the prerequisite, but now I'm not sure how to edit the code to finish. How do I edit the python code? When I open the client3.py file nothing happens.
![IMG_5729](https://user-images.githubusercontent.com/57426824/68340182-8b052800-00ab-11ea-837f-19d0d3b25624.jpg)
![IMG_5727](https://user-images.githubusercontent.com/57426824/68340197-922c3600-00ab-11ea-91b9-69a13a5de54b.jpg)
![IMG_5728](https://user-images.githubusercontent.com/57426824/68340198-922c3600-00ab-11ea-9965-6e703ad37cdc.jpg)

**Comment by jbf-insidesherpa** [comment]
@ebugarin you can edit/open the python files in the repo using any text editor e.g. notepad. However, my recommendation for you is to use an IDE (Integrated Development Environment) since that is more geared towards coding. For instance you can use Sublime Text (https://www.sublimetext.com/) or VSCode (https://code.visualstudio.com/)
