### ISSUE TITLE
Fatal: Not a git repository

### ISSUE THREAD

**Issue by KokoBell** [insidesherpa/JPMC-tech-task-1#21]
Hi, I'm getting this error when I get to the "git add -A" step of creating a patch file.

I did the setup and initializing steps at the beginning, and I'm using a Repl.it via Firefox on a Windows 10 PC.
![Screenshot 1](https://user-images.githubusercontent.com/57895838/69042569-1959a200-09fa-11ea-94b6-3d5427d6ae8f.PNG)

**Comment by jbf-insidesherpa** [comment]
@KokoBell you probably refreshed/restarted your REPL environment. REPL doesn't save the entire state. My advice to you is to start from a fresh fork of the original REPL link, redo the initialization steps and just put back your changes there and create your patch file. Avoid restarting / refreshing the REPL session. It should be quick this time around since the changes are really small and you're familiar now with how to do it.
