### ISSUE TITLE
KeyError when running Main 

### ISSUE THREAD

**Issue by ta1216** [insidesherpa/JPMC-tech-task-1#22]
Hey, been facing an issue when coding the last part of task 1, I always end up getting a KeyError: "DEF". I am unsure if I missed a step or if I did something incorrectly. Thanks for the help
I attached the code and the snip of the problem encountered if somebody has any idea where the problem could be? Thanks again

# Main
if __name__ == "__main__":
  for _ in range(N):
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
    prices = {}
    for quote in quotes:
      stock, bid_price, ask_price, price = getDataPoint(quote)
      prices[stock] = price
      print ("Quoted %s at (bid:%s, ask:%s, price:%s)" % (stock, bid_price, ask_price, price))
      print ("Ratio %s" % (getRatio(prices['ABC'],prices['DEF'])))

![image](https://user-images.githubusercontent.com/52278027/69341801-27116080-0c62-11ea-88cb-9cfee3215016.png)

**Comment by jbf-insidesherpa** [comment]
@ta1216 your code is encountering that error because the last **print** statement gets executed in the **for-loop**. That means it tries to access `prices['DEF']` even when it's not defined yet.

The proper code should look like:
```
for _ in range(N):
    .
    .
    .

print("Ratio %s" % (getRatio(prices['ABC'], prices['DEF']))
```
Notice that the **print** statement is aligned with the **for-loop** statement. This means that the **print** statement gets executed after the **for-loop** has finished and all **prices** have been defined.

**Comment by Kbarias** [comment]
I was having the same issue. I fixed it. However, this issue arises because in [slides 35 and 36](https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/repl_mod1_v4.pdf) for module 1 the last print statement is indented to be included in the loop "for _ in range(N)". These slides should be modified.
