### ISSUE TITLE
Can't create patch file

### ISSUE THREAD

**Issue by captainamiedi** [insidesherpa/JPMC-tech-task-1#23]
When i run git format-patch -1 HEAD 
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by jbf-insidesherpa** [comment]
@captainamiedi are you working thru the REPL environment? The reason why you're getting this error is most likely because the last commit is the initial commit (or no parents) of the repository, so there is no HEAD~. You probably didn't do the initialization steps correctly i.e. made an initial commit first then made another commit for the changes in client.py (or client3.py if you're working using the python3 REPL).

Please review if you did the steps correctly.

**Comment by captainamiedi** [comment]
Thanks it really helped.
