### ISSUE TITLE
python server.py syntax error

### ISSUE THREAD

**Issue by lucasbreault1** [insidesherpa/JPMC-tech-task-1#8]
Attempting to run the python server.py, but there is a syntax error. I followed all of the previous steps and even tried to install pip, but had trouble with the easy_install. (Some screenshots below) 
<img width="291" alt="Screen Shot 2019-10-21 at 7 29 11 PM" src="https://user-images.githubusercontent.com/54688815/67250556-d5df3880-f439-11e9-9431-644dbf9c8271.png">
<img width="519" alt="Screen Shot 2019-10-21 at 7 32 23 PM" src="https://user-images.githubusercontent.com/54688815/67250557-d8419280-f439-11e9-8551-1f646ee18c2d.png">

Please help!

**Comment by jbf-insidesherpa** [comment]
@lucasbreault1 you're running this incorrectly. Do not run the python command by itself on the terminal. Otherwise you'll end up in the Python shell where you can execute Python code but not a script.

For you to run the script properly, Open a new terminal, and enter "python server.py" and it should run properly.

Do the same for client.py. Open a terminal and run "python client.py" (see image below)
![image](https://user-images.githubusercontent.com/54832297/67342620-3323d880-f565-11e9-8a2c-97da70ef7834.png)
